{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "APIOAuth",
    "description": "# Introduction\nWhat does your API do?\n\n# Overview\nThings that the developers should know about\n\n# Authentication\nWhat is the preferred way of using the API?\n\n# Error Codes\nWhat errors and status codes can a user expect?\n\n# Rate limit\nIs there a limit to the number of requests an user can send?",
    "contact": {},
    "x-jentic-source-url": "https://api.swaggerhub.com/apis/test4364/apio-auth3/1.0/swagger.json"
  },
  "host": "testpaport.enfs.com",
  "basePath": "/",
  "securityDefinitions": {},
  "schemes": [
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/paportoauth529/odata2/token": {
      "post": {
        "description": "Get Authorization token",
        "summary": "Get Authorization Token",
        "tags": [
          "Misc"
        ],
        "operationId": "Paportoauth529Odata2TokenPost",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/PAPortOdata529/odata/v1.2/Balance": {
      "get": {
        "description": "Get balances for a given Account, Fund and Valuation Date\nFund = 0 for \"All Funds\"",
        "summary": "Get Account Balances",
        "tags": [
          "Misc"
        ],
        "operationId": "PAPortOdata529OdataV12BalanceGet",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "AccountNumber",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "Account Number in the system"
          },
          {
            "name": "FundId",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": "Fund Id - 0 for all funds, or specific valid fund id"
          },
          {
            "name": "ValuationDate",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "Balances as of given date"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/PAPortOdata529/odata/v1.2/RecentActivity": {
      "get": {
        "description": "Get Activities for an account for a specified date range",
        "summary": "Get Account Activities",
        "tags": [
          "Misc"
        ],
        "operationId": "PAPortOdata529OdataV12RecentActivityGet",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "AccountNumber",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "Base 64 encoded value of Account Number"
          },
          {
            "name": "EndDate",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "End Date to retrieve activities"
          },
          {
            "name": "StartDate",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "Start Date to retrieve activities"
          },
          {
            "name": "_",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int64",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/paportodata529/odata/v1.2/Accounts('10010')/Addresses": {
      "put": {
        "description": "Update Registration, Alternate, and/or Temporary address for an account.",
        "summary": "Update Account Address",
        "tags": [
          "Misc"
        ],
        "operationId": "Paportodata529OdataV12Accounts10010AddressesPut",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/UpdateAccountAddressRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/paportodata529/odata/v1.2/Accounts": {
      "post": {
        "description": "Create New Account",
        "summary": "Create New Account",
        "tags": [
          "Misc"
        ],
        "operationId": "Paportodata529OdataV12AccountsPost",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/CreateNewAccountRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    }
  },
  "definitions": {
    "UpdateAccountAddressRequest": {
      "title": "UpdateAccountAddressRequest",
      "example": {
        "AccountAddressIndicator": 0,
        "Registration": {
          "NameLines": "Laura and Bob Sanderson",
          "AddressLines": "123 Main St.\nIRVINE, CA 92612",
          "CountryCode": 0,
          "PostalZip": 92612,
          "VoicePhone": 2102005500,
          "AltPhone": 3103004550,
          "FaxPhone": "",
          "EmailAddress": "prithvi.hariharan@enfs.com",
          "DoNotAcceptUSPSUpdate": 0
        },
        "Alternate": {
          "NameLines": "Name",
          "AddressLines": "123 Main Street\nIRVINE, CA 92614",
          "CountryCode": 0,
          "PostalZip": 92614,
          "VoicePhone": "",
          "AltPhone": "",
          "FaxPhone": "",
          "EmailAddress": "",
          "DoNotAcceptUSPSUpdate": 0
        },
        "Seasonal": null
      },
      "type": "object",
      "properties": {
        "AccountAddressIndicator": {
          "type": "integer",
          "format": "int32"
        },
        "Registration": {
          "$ref": "#/definitions/Registration"
        },
        "Alternate": {
          "$ref": "#/definitions/Alternate"
        },
        "Seasonal": {
          "type": "string"
        }
      },
      "required": [
        "AccountAddressIndicator",
        "Registration",
        "Alternate",
        "Seasonal"
      ]
    },
    "Registration": {
      "title": "Registration",
      "example": {
        "NameLines": "Laura and Bob Sanderson",
        "AddressLines": "123 Main St.\nIRVINE, CA 92612",
        "CountryCode": 0,
        "PostalZip": 92612,
        "VoicePhone": 2102005500,
        "AltPhone": 3103004550,
        "FaxPhone": "",
        "EmailAddress": "prithvi.hariharan@enfs.com",
        "DoNotAcceptUSPSUpdate": 0
      },
      "type": "object",
      "properties": {
        "NameLines": {
          "type": "string"
        },
        "AddressLines": {
          "type": "string"
        },
        "CountryCode": {
          "type": "integer",
          "format": "int32"
        },
        "PostalZip": {
          "type": "string"
        },
        "VoicePhone": {
          "type": "string"
        },
        "AltPhone": {
          "type": "string"
        },
        "FaxPhone": {
          "type": "string"
        },
        "EmailAddress": {
          "type": "string"
        },
        "DoNotAcceptUSPSUpdate": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "NameLines",
        "AddressLines",
        "CountryCode",
        "PostalZip",
        "VoicePhone",
        "AltPhone",
        "FaxPhone",
        "EmailAddress",
        "DoNotAcceptUSPSUpdate"
      ]
    },
    "Alternate": {
      "title": "Alternate",
      "example": {
        "NameLines": "Name",
        "AddressLines": "123 Main Street\nIRVINE, CA 92614",
        "CountryCode": 0,
        "PostalZip": 92614,
        "VoicePhone": "",
        "AltPhone": "",
        "FaxPhone": "",
        "EmailAddress": "",
        "DoNotAcceptUSPSUpdate": 0
      },
      "type": "object",
      "properties": {
        "NameLines": {
          "type": "string"
        },
        "AddressLines": {
          "type": "string"
        },
        "CountryCode": {
          "type": "integer",
          "format": "int32"
        },
        "PostalZip": {
          "type": "string"
        },
        "VoicePhone": {
          "type": "string"
        },
        "AltPhone": {
          "type": "string"
        },
        "FaxPhone": {
          "type": "string"
        },
        "EmailAddress": {
          "type": "string"
        },
        "DoNotAcceptUSPSUpdate": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "NameLines",
        "AddressLines",
        "CountryCode",
        "PostalZip",
        "VoicePhone",
        "AltPhone",
        "FaxPhone",
        "EmailAddress",
        "DoNotAcceptUSPSUpdate"
      ]
    },
    "CreateNewAccountRequest": {
      "title": "CreateNewAccountRequest",
      "example": {
        "AccountNumber": "",
        "InvestmentProgram": 1,
        "AccountType": 1,
        "NamesTag": [
          "SHAREHOLDER NAME = First Name",
          "M.I = test ",
          "LAST NAME = CA"
        ],
        "TaxPayerType": 1,
        "CountryOfTaxResidence": 0,
        "CountryOfCitizenship": 0,
        "Gender": 2,
        "DateOfBirth": "1959-08-01",
        "SSNOrTINIndicator": 1,
        "SSNOrTIN": 900038894,
        "RepInformation": {
          "DealerNumber": 90496,
          "BranchNumber": 25,
          "RepNumber": 0
        },
        "BankInformation": {
          "BankRoutingNumber": 322281507,
          "AccountNumber": 1521421,
          "AccountName": "Account Name",
          "AccountType": 1,
          "BankName": "Bank Name",
          "BankNickname": "Nick name"
        },
        "Addresses": {
          "AccountAddressIndicator": 0,
          "Registration": {
            "NameLines": "Name Line",
            "AddressLines": "Address Line",
            "PostalZip": 12345,
            "CountryCode": 0,
            "VoicePhone": 2522220252,
            "AltPhone": 258222,
            "FaxPhone": "",
            "EmailAddress": "jothi.r@enfs.com",
            "DoNotAcceptUSPSUpdate": 0
          }
        },
        "DividendAndCapitalGains": [
          {
            "AllInvestments": 1,
            "STCG": 1,
            "LTCG": 1
          }
        ],
        "DocumentDelivery": [
          {
            "FormCategoryId": 1,
            "DeliveryMode": 2
          },
          {
            "FormCategoryId": 2,
            "DeliveryMode": 2
          },
          {
            "FormCategoryId": 3,
            "DeliveryMode": 2
          },
          {
            "FormCategoryId": 5,
            "DeliveryMode": 2
          },
          {
            "FormCategoryId": 6,
            "DeliveryMode": 2
          }
        ]
      },
      "type": "object",
      "properties": {
        "AccountNumber": {
          "type": "string"
        },
        "InvestmentProgram": {
          "type": "integer",
          "format": "int32"
        },
        "AccountType": {
          "type": "integer",
          "format": "int32"
        },
        "NamesTag": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "TaxPayerType": {
          "type": "integer",
          "format": "int32"
        },
        "CountryOfTaxResidence": {
          "type": "integer",
          "format": "int32"
        },
        "CountryOfCitizenship": {
          "type": "integer",
          "format": "int32"
        },
        "Gender": {
          "type": "integer",
          "format": "int32"
        },
        "DateOfBirth": {
          "type": "string"
        },
        "SSNOrTINIndicator": {
          "type": "integer",
          "format": "int32"
        },
        "SSNOrTIN": {
          "type": "string"
        },
        "RepInformation": {
          "$ref": "#/definitions/RepInformation"
        },
        "BankInformation": {
          "$ref": "#/definitions/BankInformation"
        },
        "Addresses": {
          "$ref": "#/definitions/Addresses"
        },
        "DividendAndCapitalGains": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/DividendAndCapitalGain"
          }
        },
        "DocumentDelivery": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/DocumentDelivery"
          }
        }
      },
      "required": [
        "AccountNumber",
        "InvestmentProgram",
        "AccountType",
        "NamesTag",
        "TaxPayerType",
        "CountryOfTaxResidence",
        "CountryOfCitizenship",
        "Gender",
        "DateOfBirth",
        "SSNOrTINIndicator",
        "SSNOrTIN",
        "RepInformation",
        "BankInformation",
        "Addresses",
        "DividendAndCapitalGains",
        "DocumentDelivery"
      ]
    },
    "RepInformation": {
      "title": "RepInformation",
      "example": {
        "DealerNumber": 90496,
        "BranchNumber": 25,
        "RepNumber": 0
      },
      "type": "object",
      "properties": {
        "DealerNumber": {
          "type": "integer",
          "format": "int32"
        },
        "BranchNumber": {
          "type": "string"
        },
        "RepNumber": {
          "type": "string"
        }
      },
      "required": [
        "DealerNumber",
        "BranchNumber",
        "RepNumber"
      ]
    },
    "BankInformation": {
      "title": "BankInformation",
      "example": {
        "BankRoutingNumber": 322281507,
        "AccountNumber": 1521421,
        "AccountName": "Account Name",
        "AccountType": 1,
        "BankName": "Bank Name",
        "BankNickname": "Nick name"
      },
      "type": "object",
      "properties": {
        "BankRoutingNumber": {
          "type": "string"
        },
        "AccountNumber": {
          "type": "string"
        },
        "AccountName": {
          "type": "string"
        },
        "AccountType": {
          "type": "integer",
          "format": "int32"
        },
        "BankName": {
          "type": "string"
        },
        "BankNickname": {
          "type": "string"
        }
      },
      "required": [
        "BankRoutingNumber",
        "AccountNumber",
        "AccountName",
        "AccountType",
        "BankName",
        "BankNickname"
      ]
    },
    "Addresses": {
      "title": "Addresses",
      "example": {
        "AccountAddressIndicator": 0,
        "Registration": {
          "NameLines": "Name Line",
          "AddressLines": "Address Line",
          "PostalZip": 12345,
          "CountryCode": 0,
          "VoicePhone": 2522220252,
          "AltPhone": 258222,
          "FaxPhone": "",
          "EmailAddress": "jothi.r@enfs.com",
          "DoNotAcceptUSPSUpdate": 0
        }
      },
      "type": "object",
      "properties": {
        "AccountAddressIndicator": {
          "type": "integer",
          "format": "int32"
        },
        "Registration": {
          "$ref": "#/definitions/Registration"
        }
      },
      "required": [
        "AccountAddressIndicator",
        "Registration"
      ]
    },
    "DividendAndCapitalGain": {
      "title": "DividendAndCapitalGain",
      "example": {
        "AllInvestments": 1,
        "STCG": 1,
        "LTCG": 1
      },
      "type": "object",
      "properties": {
        "AllInvestments": {
          "type": "integer",
          "format": "int32"
        },
        "STCG": {
          "type": "integer",
          "format": "int32"
        },
        "LTCG": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "AllInvestments",
        "STCG",
        "LTCG"
      ]
    },
    "DocumentDelivery": {
      "title": "DocumentDelivery",
      "example": {
        "FormCategoryId": 1,
        "DeliveryMode": 2
      },
      "type": "object",
      "properties": {
        "FormCategoryId": {
          "type": "integer",
          "format": "int32"
        },
        "DeliveryMode": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "FormCategoryId",
        "DeliveryMode"
      ]
    }
  },
  "tags": [
    {
      "name": "Misc",
      "description": ""
    }
  ]
}