{
  "openapi": "3.0.0",
  "info": {
    "title": "API-NE-EstructuraErrores",
    "description": "La API tiene como finalidad exponer la correcta utilizacion de la estructura de codigos de errores \n",
    "version": "1.0.0",
    "x-metadata-api": {
      "metadataNegocio": {
        "tribuOwner": "Tribu",
        "negocio": "Ejemplo",
        "producto": "Ejemplo",
        "dominio": "Ejemplo",
        "subDominio": "Ejemplo",
        "productoOwner": "Ejemplo",
        "squadOwner": "Chapter",
        "arquitecto": "arquitecto",
        "tipoApi": "Negocio",
        "tipoCanal": "Canales"
      },
      "metadataTecnica": {
        "tipoExposicion": "Interna",
        "tipoWorkload": "Microservicio",
        "lenguajeProgramacion": "Java",
        "nombreServicioBackend": "ms-ne-estructura-errores",
        "consumidorApi": "Apis Canal",
        "codigoAplicacion": "Prueba",
        "mecanismoAutenticacion": "ApiKey"
      }
    },
    "x-jentic-source-url": "https://api.swaggerhub.com/apis/jhon.hernandez/API-NE-EstructuraErrores/1.0.0/swagger.json"
  },
  "servers": [
    {
      "description": "SwaggerHub API Auto Mocking",
      "url": "https://virtserver.swaggerhub.com/PacificoSegurosPeru/ne-Estructura-Errore/1.0.0"
    },
    {
      "url": "https://apimgmt-pacificodesa.azure-api.net/ne-Estructura-Errores/v1",
      "description": "Servidor de Desarrollo"
    },
    {
      "url": "https://apimgmt-pacificocert.azure-api.net/ne-Estructura-Errores/v1",
      "description": "Servidor de Calidad"
    },
    {
      "url": "https://apimgmt-pacificoprod.azure-api.net/ne-Estructura-Errores/v1",
      "description": "Servidor de Producci\u00f3n"
    }
  ],
  "paths": {
    "/validacion/poliza": {
      "post": {
        "summary": "Valida si la p\u00f3liza tiene uno o varios siniestros.",
        "operationId": "validarSiniestros",
        "tags": [
          "ValidacionSiniestro"
        ],
        "description": "Valida si la p\u00f3liza tiene uno o varios siniestros seg\u00fan n\u00famero y estado de la p\u00f3liza.\n",
        "parameters": [
          {
            "$ref": "https://api.swaggerhub.com/domains/PacificoSegurosPeru/Domain-Base/1.0.0#/components/parameters/Header-Transaccion-Id"
          },
          {
            "$ref": "https://api.swaggerhub.com/domains/PacificoSegurosPeru/Domain-Base/1.0.0#/components/parameters/Header-Aplicacion-Id"
          },
          {
            "$ref": "https://api.swaggerhub.com/domains/PacificoSegurosPeru/Domain-Base/1.0.0#/components/parameters/Header-Nombre-Aplicacion"
          },
          {
            "$ref": "https://api.swaggerhub.com/domains/PacificoSegurosPeru/Domain-Base/1.0.0#/components/parameters/Header-Usuario-Consumidor-Id"
          },
          {
            "$ref": "https://api.swaggerhub.com/domains/PacificoSegurosPeru/Domain-Base/1.0.0#/components/parameters/Header-Nombre-Servicio-Consumidor"
          },
          {
            "$ref": "https://api.swaggerhub.com/domains/PacificoSegurosPeru/Domain-Base/1.0.0#/components/parameters/Header-Ocp-Apim-Subscription-Key"
          },
          {
            "$ref": "https://api.swaggerhub.com/domains/PacificoSegurosPeru/Domain-Base/1.0.0#/components/parameters/Header-Token-Seguridad"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PeticionValidacion"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Validaci\u00f3n realizada con \u00e9xito.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RespuestaValidacion"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error400"
                },
                "examples": {
                  "FSL-VF-001 - Error de validacion": {
                    "$ref": "#/components/examples/validacion400-001"
                  },
                  "FSL-VF-002 - Formato inv\u00e1lido": {
                    "$ref": "#/components/examples/validacion400-002"
                  },
                  "FSL-VF-003 -  Campos Obligatorios": {
                    "$ref": "#/components/examples/validacion400-003"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error403"
                },
                "examples": {
                  "FFL-DF-403 - Sin permisos para eliminar": {
                    "$ref": "#/components/examples/validacion403-001"
                  },
                  "FFL-DF-403 - Permisos modificacion": {
                    "$ref": "#/components/examples/validacion403-002"
                  },
                  "FFL-DF-403 -  Permisos insuficientes": {
                    "$ref": "#/components/examples/validacion403-003"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error404"
                },
                "examples": {
                  "FFL-DF-404 - Recurso no encontrado": {
                    "$ref": "#/components/examples/validacion404-001"
                  },
                  "FFL-DF-404 - Poliza no encontrada": {
                    "$ref": "#/components/examples/validacion404-002"
                  },
                  "FFL-DF-404 - Punto final no encontrado": {
                    "$ref": "#/components/examples/validacion404-003"
                  }
                }
              }
            }
          },
          "409": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error409"
                },
                "examples": {
                  "FFL-DF-409 - poliza en proceso": {
                    "$ref": "#/components/examples/validacion409-001"
                  },
                  "FFL-DF-409 - Incompatible": {
                    "$ref": "#/components/examples/validacion409-002"
                  },
                  "FFL-DF-409 - Poliza inactiva": {
                    "$ref": "#/components/examples/validacion409-003"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500"
                }
              }
            }
          }
        }
      }
    }
  },
  "security": [
    {
      "ApiKey": []
    },
    {
      "TokenJWT": []
    }
  ],
  "components": {
    "examples": {
      "validacion400-001": {
        "value": {
          "error": {
            "tipo": "FUNCIONAL",
            "codigo": "FSL-VF-001",
            "mensaje": "Error de validacion"
          }
        }
      },
      "validacion400-002": {
        "value": {
          "error": {
            "tipo": "FUNCIONAL",
            "codigo": "FSL-VF-002",
            "mensaje": "El formato de la poliza es incorrecto"
          }
        }
      },
      "validacion400-003": {
        "value": {
          "error": {
            "tipo": "FUNCIONAL",
            "codigo": "FSL-VF-003",
            "mensaje": "Faltan campos obligatorios en la solicitud."
          }
        }
      },
      "validacion403-001": {
        "value": {
          "error": {
            "tipo": "FUNCIONAL",
            "codigo": "FFL-DF-001",
            "mensaje": "No tienes permiso para eliminar el archivo de este requerimiento."
          }
        }
      },
      "validacion403-002": {
        "value": {
          "error": {
            "tipo": "FUNCIONAL",
            "codigo": "FFL-DF-002",
            "mensaje": "No tienes permiso para modificar este requerimiento."
          }
        }
      },
      "validacion403-003": {
        "value": {
          "error": {
            "tipo": "FUNCIONAL",
            "codigo": "FFL-DF-003",
            "mensaje": "No tienes permiso para acceder a los recursos de otro usuario."
          }
        }
      },
      "validacion404-001": {
        "value": {
          "error": {
            "tipo": "FUNCIONAL",
            "codigo": "FFL-DF-001",
            "mensaje": "El recurso solicitado no se encontr\u00f3 en la base de datos."
          }
        }
      },
      "validacion404-002": {
        "value": {
          "error": {
            "tipo": "FUNCIONAL",
            "codigo": "FFL-DF-002",
            "mensaje": "la poliza proporcionada no existe. Verifica el numero de poliza"
          }
        }
      },
      "validacion404-003": {
        "value": {
          "error": {
            "tipo": "FUNCIONAL",
            "codigo": "FFL-DF-003",
            "mensaje": "El punto final solicitado no existe en esta API. Aseg\u00farate de que la ruta es correcta y que el recurso        est\u00e1 disponible."
          }
        }
      },
      "validacion409-001": {
        "value": {
          "error": {
            "tipo": "FUNCIONAL",
            "codigo": "FFL-DF-001",
            "mensaje": "Ya se ha enviado una solicitud para esta poliza. Espere a que se complete antes de hacer otra consulta."
          }
        }
      },
      "validacion409-002": {
        "value": {
          "error": {
            "tipo": "FUNCIONAL",
            "codigo": "FFL-DF-002",
            "mensaje": "La p\u00f3liza tiene un estado incompatible para realizar la consulta de siniestros."
          }
        }
      },
      "validacion409-003": {
        "value": {
          "error": {
            "tipo": "FUNCIONAL",
            "codigo": "FFL-DF-003",
            "mensaje": "La poliza  est\u00e1 inactiva y no se pueden consultar los siniestros asociados."
          }
        }
      }
    },
    "schemas": {
      "PeticionValidacion": {
        "type": "object",
        "properties": {
          "datos": {
            "$ref": "#/components/schemas/DatosPedidoValidacion"
          }
        }
      },
      "DatosPedidoValidacion": {
        "required": [
          "poliza"
        ],
        "type": "object",
        "description": "Modelo de request para validar siniestros",
        "properties": {
          "poliza": {
            "type": "string",
            "description": "N\u00famero de p\u00f3liza",
            "example": "3020098504"
          }
        }
      },
      "RespuestaValidacion": {
        "type": "object",
        "properties": {
          "datos": {
            "$ref": "#/components/schemas/DatosRespuestaValidacion"
          }
        }
      },
      "DatosRespuestaValidacion": {
        "description": "Respuesta con datos de cantidad de siniestros",
        "type": "object",
        "properties": {
          "cantidadSiniestros": {
            "type": "integer",
            "description": "Cantidad de siniestros",
            "example": 0
          }
        }
      },
      "Error400": {
        "type": "object",
        "properties": {
          "error": {
            "$ref": "#/components/schemas/ErrorRespuesta400"
          }
        }
      },
      "ErrorRespuesta400": {
        "type": "object",
        "properties": {
          "tipo": {
            "type": "string",
            "enum": [
              "FUNCIONAL",
              "SISTEMA"
            ]
          },
          "codigo": {
            "type": "string"
          },
          "mensaje": {
            "type": "string"
          }
        }
      },
      "Error403": {
        "type": "object",
        "properties": {
          "error": {
            "$ref": "#/components/schemas/ErrorRespuesta403"
          }
        }
      },
      "ErrorRespuesta403": {
        "type": "object",
        "properties": {
          "tipo": {
            "type": "string",
            "enum": [
              "FUNCIONAL",
              "SISTEMA"
            ]
          },
          "codigo": {
            "type": "string"
          },
          "mensaje": {
            "type": "string"
          }
        }
      },
      "Error404": {
        "type": "object",
        "properties": {
          "error": {
            "$ref": "#/components/schemas/ErrorRespuesta404"
          }
        }
      },
      "ErrorRespuesta404": {
        "type": "object",
        "properties": {
          "tipo": {
            "type": "string",
            "enum": [
              "FUNCIONAL",
              "SISTEMA"
            ]
          },
          "codigo": {
            "type": "string"
          },
          "mensaje": {
            "type": "string"
          }
        }
      },
      "Error409": {
        "type": "object",
        "properties": {
          "error": {
            "$ref": "#/components/schemas/ErrorRespuesta409"
          }
        }
      },
      "ErrorRespuesta409": {
        "type": "object",
        "properties": {
          "tipo": {
            "type": "string",
            "enum": [
              "FUNCIONAL",
              "SISTEMA"
            ]
          },
          "codigo": {
            "type": "string"
          },
          "mensaje": {
            "type": "string"
          }
        }
      },
      "Error500": {
        "type": "object",
        "properties": {
          "error": {
            "$ref": "#/components/schemas/ErrorRespuesta500"
          }
        }
      },
      "ErrorRespuesta500": {
        "type": "object",
        "properties": {
          "tipo": {
            "type": "string",
            "enum": [
              "FUNCIONAL",
              "SISTEMA"
            ],
            "example": "SISTEMA"
          },
          "codigo": {
            "type": "string",
            "example": "SSL-DF-500"
          },
          "mensaje": {
            "type": "string",
            "example": "Error interno del servidor"
          }
        }
      }
    },
    "securitySchemes": {
      "ApiKey": {
        "type": "apiKey",
        "in": "header",
        "name": "Ocp-Apim-Subscription-Key"
      },
      "TokenJWT": {
        "description": "JWT bearer token de autenticaci\u00f3n.",
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}