{
  "openapi": "3.0.0",
  "info": {
    "description": "Wallet catalog is basically an feature containing different wallet types.Helps in carrying various task and services",
    "version": "1.0.0",
    "title": "Wallet Action APIs",
    "x-jentic-source-url": "https://api.swaggerhub.com/apis/igtbdigital/Action-Wallets-KD/1.0.0/swagger.json"
  },
  "servers": [
    {
      "url": "https://virtserver.swaggerhub.com/igtbdigital/Action-Wallets-KD/1.0.0"
    }
  ],
  "paths": {
    "/v1/wallets": {
      "post": {
        "tags": [
          "Wallet"
        ],
        "summary": "Draft / Initiate to Create a wallet",
        "description": "Raise draft / initiate request on channel to create new wallet",
        "operationId": "createWallet",
        "parameters": [
          {
            "$ref": "https://api.swaggerhub.com/domains/igtbdigital/commons/1.5.3#/components/parameters/HdrDomainId"
          },
          {
            "$ref": "https://api.swaggerhub.com/domains/igtbdigital/commons/1.5.3#/components/parameters/HdrRequestId"
          },
          {
            "$ref": "https://api.swaggerhub.com/domains/igtbdigital/commons/1.5.3#/components/parameters/HdrAuth"
          },
          {
            "$ref": "https://api.swaggerhub.com/domains/igtbdigital/commons/1.5.3#/components/parameters/HdrSharedKey"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateWalletRequest"
              }
            }
          },
          "description": "Wallet details to add",
          "required": true
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/Response_200"
          },
          "201": {
            "$ref": "#/components/responses/Response_201"
          },
          "422": {
            "description": "Request failed validation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ValErrorResponse"
                },
                "examples": {
                  "response": {
                    "value": {
                      "channelSeqId": "C250720170000001",
                      "resMsg": "Request failed validation",
                      "valErrors": [
                        {
                          "code": "ERRMSG0001",
                          "field": "Name",
                          "message": "Mandatory field missing."
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "500": {
            "$ref": "#/components/responses/Response_500"
          }
        }
      }
    },
    "/v1/wallets/{walletId}": {
      "put": {
        "tags": [
          "Wallet"
        ],
        "summary": "Draft / Initiate to Update existing Wallet.",
        "description": "Raise draft / initiate request on channel to update existing Wallet.\n  \nFor update request, as a basic rule, it is expected for consumer to provide a final desired snashot of a Wallet and associated Accounts in request payload.\n\n- When **Only Wallet is updated**, without any account level change, consumer is expected to supply:\n  - **All** (modified/unmodified) attributes of Wallet\n  - **All** existing Accounts with related fields and account \"action\" as **update**\n- When Wallet is **updated**, and account is **added**, consumer is expected to supply:\n  - **All** (modified/unmodified) attributes of Wallet\n  - **All** existing Accounts with related fields and account \"action\" as **update**\n  - **new** account with account \"action\" as **create**\n- When Wallet is **updated**, and account is **updated**, consumer is expected to supply:\n  - **All** (modified/unmodified) attributes of Wallet\n  - **All** existing + **updated** Accounts with related fields and account \"action\" as **update**\n- When Wallet is **updated**, and account is **deleted**, consumer is expected to supply:\n  - **All** (modified/unmodified) attributes of Wallet\n  - **All** existing Accounts (except **deleted** one) with related fields and account \"action\" as **update**\n",
        "operationId": "updateWallet",
        "parameters": [
          {
            "$ref": "https://api.swaggerhub.com/domains/igtbdigital/commons/1.5.3#/components/parameters/HdrDomainId"
          },
          {
            "$ref": "https://api.swaggerhub.com/domains/igtbdigital/commons/1.5.3#/components/parameters/HdrRequestId"
          },
          {
            "$ref": "https://api.swaggerhub.com/domains/igtbdigital/commons/1.5.3#/components/parameters/HdrAuth"
          },
          {
            "$ref": "https://api.swaggerhub.com/domains/igtbdigital/commons/1.5.3#/components/parameters/HdrSharedKey"
          },
          {
            "name": "walletId",
            "in": "path",
            "description": "Unique Id of a wallet, to be modified.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateWalletRequest"
              }
            }
          },
          "description": "Update Wallet Request body",
          "required": true
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/Response_200"
          },
          "201": {
            "$ref": "#/components/responses/Response_201"
          },
          "422": {
            "description": "Request failed validation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ValErrorResponse"
                },
                "examples": {
                  "response": {
                    "value": {
                      "channelSeqId": "C250720170000001",
                      "resMsg": "Request failed validation",
                      "valErrors": [
                        {
                          "code": "ERRMSG0001",
                          "field": "Generic",
                          "message": "Wallet details duplicated."
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "500": {
            "$ref": "#/components/responses/Response_500"
          }
        }
      },
      "delete": {
        "tags": [
          "Wallet"
        ],
        "summary": "Draft / Initiate to Delete existing Wallet",
        "description": "Raise draft / initiate request on channel to delete existing Wallet.\n\nFor delete request, it is expected for consumer to mandatorily provide **WalletId** and **type** in payload. Other Wallet attributes and associated Accounts need not be passed.\n",
        "operationId": "initiateDeleteWallet",
        "parameters": [
          {
            "$ref": "https://api.swaggerhub.com/domains/igtbdigital/commons/1.5.3#/components/parameters/HdrDomainId"
          },
          {
            "$ref": "https://api.swaggerhub.com/domains/igtbdigital/commons/1.5.3#/components/parameters/HdrRequestId"
          },
          {
            "$ref": "https://api.swaggerhub.com/domains/igtbdigital/commons/1.5.3#/components/parameters/HdrAuth"
          },
          {
            "$ref": "https://api.swaggerhub.com/domains/igtbdigital/commons/1.5.3#/components/parameters/HdrSharedKey"
          },
          {
            "name": "walletId",
            "in": "path",
            "description": "Unique instance Id of a resource at Domain level, to be deleted.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DeleteWalletRequest"
              }
            }
          },
          "description": "Delete Wallet Request body",
          "required": true
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/Response_200"
          },
          "201": {
            "$ref": "#/components/responses/Response_201"
          },
          "422": {
            "description": "Request failed validation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ValErrorResponse"
                },
                "examples": {
                  "response": {
                    "value": {
                      "channelSeqId": "C250720170000001",
                      "resMsg": "Request failed validation",
                      "valErrors": [
                        {
                          "code": "ERRMSG0001",
                          "field": "Generic",
                          "message": "Wallet details does not exists."
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "500": {
            "$ref": "#/components/responses/Response_500"
          }
        }
      }
    },
    "/v1/wallets/{channelSeqId}/state": {
      "put": {
        "tags": [
          "Wallet"
        ],
        "summary": "Update Wallet Request Status",
        "description": "Request to update the wallet which is still parked in the channel domain. Request identified by channelSeqId. Request accepted for states includes reject, cancel, release.\n- `reject` indicates approver rejects the transaction in workflow.\n- `cancel` indicates Initiator cancels the request himself.\n- `release` indicates it to be released to downstream post all approvals.\n- `trash` is to mark the request as trashed, so that it doesn't appear in user's queue. Only those requests, that are in draft, that are initiated but pending first approval yet and that are failed/rejected (for some reason) are eligible to be trashed.",
        "operationId": "updateWalletStatus",
        "parameters": [
          {
            "$ref": "https://api.swaggerhub.com/domains/igtbdigital/commons/1.5.3#/components/parameters/HdrDomainId"
          },
          {
            "$ref": "https://api.swaggerhub.com/domains/igtbdigital/commons/1.5.3#/components/parameters/HdrRequestId"
          },
          {
            "$ref": "https://api.swaggerhub.com/domains/igtbdigital/commons/1.5.3#/components/parameters/HdrAuth"
          },
          {
            "$ref": "https://api.swaggerhub.com/domains/igtbdigital/commons/1.5.3#/components/parameters/HdrSharedKey"
          },
          {
            "name": "channelSeqId",
            "in": "path",
            "description": "identifier of the original request whose status needs to be updated",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ReleaseRequestBody"
              }
            }
          },
          "description": "Updated wallet request Status",
          "required": true
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/Response_200"
          },
          "202": {
            "$ref": "#/components/responses/Response_202"
          },
          "409": {
            "$ref": "#/components/responses/Response_409"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "CreateWalletRequest": {
        "type": "object",
        "properties": {
          "context": {
            "$ref": "#/components/schemas/Context"
          },
          "payload": {
            "$ref": "#/components/schemas/Wallet"
          }
        },
        "required": [
          "context",
          "payload"
        ],
        "example": {
          "context": {
            "action": "initiate",
            "serviceKey": "wallet/administration",
            "userAction": "add"
          },
          "payload": {
            "name": "John",
            "description": "Creditcards Wallet",
            "currencyCode": "USD",
            "entityId": "TCS01"
          }
        }
      },
      "UpdateWalletRequest": {
        "type": "object",
        "properties": {
          "context": {
            "$ref": "#/components/schemas/Context"
          },
          "payload": {
            "$ref": "#/components/schemas/Wallet"
          }
        },
        "required": [
          "context",
          "payload"
        ],
        "example": {
          "context": {
            "channelSeqId": "C250720170000001",
            "action": "initiate",
            "domainResource": {
              "seqId": "D201710310121336"
            },
            "serviceKey": "wallet/administration",
            "userAction": "update"
          },
          "payload": {
            "walletId": "D201710310121336",
            "name": "Sam",
            "description": "Creditcards Wallet",
            "currencyCode": "INR",
            "entityId": "TCS01"
          }
        }
      },
      "DeleteWalletRequest": {
        "type": "object",
        "properties": {
          "context": {
            "$ref": "#/components/schemas/Context"
          },
          "payload": {
            "$ref": "#/components/schemas/Wallet"
          }
        },
        "required": [
          "context",
          "payload"
        ],
        "example": {
          "context": {
            "channelSeqId": "C250720170000001",
            "action": "initiate",
            "domainResource": {
              "seqId": "D201710310121336"
            },
            "serviceKey": "wallet/administration",
            "userAction": "delete"
          },
          "payload": {
            "type": "Administration",
            "walletId": "D201710310121336"
          }
        }
      },
      "Wallet": {
        "type": "object",
        "properties": {
          "walletId": {
            "type": "string",
            "example": "D201710310121336",
            "description": "Wallet id. This will be generated by backend on platform release request. Mandatory for updating and deleting wallet from all wallet type."
          },
          "name": {
            "type": "string",
            "example": "John",
            "description": "Name of Wallet. Mandatory for all Wallet type. Editable on update.",
            "maxLength": 150
          },
          "description": {
            "type": "string",
            "example": "Creditcards Wallet",
            "description": "Name of Wallet. Mandatory for wallet type. Editable on update.",
            "maxLength": 150
          },
          "currencyCode": {
            "type": "string",
            "example": "USD",
            "description": "Currency of amount transfered per day for a wallet.",
            "maxLength": 3
          },
          "entityId": {
            "type": "string",
            "example": "TCS01",
            "description": "Entity id of the corporate.",
            "maxLength": 30
          }
        }
      },
      "ChannelRequestRelation": {
        "type": "object",
        "properties": {
          "relType": {
            "type": "string",
            "description": "Type of the relation with other channel request. edit-source - indicates the related request is the one, which is taken as source of input for editing",
            "example": "edit-source",
            "enum": [
              "edit-source"
            ]
          },
          "channelSeqId": {
            "type": "string",
            "description": "Unique reference (channelSeqId) to related channel request.",
            "example": "C250720170000000",
            "format": "uuid"
          }
        },
        "required": [
          "relType",
          "channelSeqId"
        ]
      },
      "Context": {
        "type": "object",
        "properties": {
          "channelSeqId": {
            "type": "string",
            "description": "Unique instance Id of a request generated by the channel on submitting first draft/initiate request. For all subsequent actions (on the same request), this field should be populated in a request. Mandatory for resave draft, draft to initiate, release, reject, cancel, trash, standalone_revalidate requests.",
            "example": "C250720170000001",
            "format": "uuid"
          },
          "action": {
            "type": "string",
            "description": "Indicates what action is requested to be carried out.",
            "example": "initiate",
            "enum": [
              "draft",
              "initiate",
              "validate",
              "release",
              "reject",
              "cancel",
              "trash"
            ]
          },
          "remarks": {
            "type": "string",
            "example": "Remarks",
            "description": "Rejection / Failure reason. Mandatory for reject, cancel requests."
          },
          "domainResource": {
            "type": "object",
            "properties": {
              "seqId": {
                "type": "string",
                "description": "Unique instance Id of a resource at Domain level. Mandatory when request is about Update / Delete operation on an existing resource. Domain resources are SweepStructure, FundTransfer, Mandate, Invoice etc.",
                "example": "SS1008T234",
                "format": "uuid"
              }
            }
          },
          "serviceKey": {
            "type": "string",
            "example": "lqdy/swps",
            "description": "Service Key definition represents product/subproduct offering in Digital channel. Mandatory for draft, initiate requests. Ignored for other requests."
          },
          "userAction": {
            "type": "string",
            "example": "execute",
            "description": "Represents a function to be performed on a domain resource as per PSF mapping defined for Digital Platform. Applicable for draft, initiate requests. Examples add, amend, delete, execute, hold, unhold"
          },
          "relatedChnlRequests": {
            "type": "array",
            "description": "To be populated with a list of relations for this request, with other channel initiated requests. Applicable only for draft & initiate requests, whichever is raised first. Useful when, for example, user chooses to edit previously rejected request, list can hold information about original channel request",
            "items": {
              "$ref": "#/components/schemas/ChannelRequestRelation"
            },
            "example": [
              {
                "relType": "edit-source",
                "channelSeqId": "C250720170000000"
              }
            ]
          }
        },
        "required": [
          "action"
        ]
      },
      "Response": {
        "type": "object",
        "description": "Response Object defining the outcome of a  Request",
        "properties": {
          "channelSeqId": {
            "description": "Unique identification as assigned by the Digital Platform when action request is initiated.",
            "type": "string",
            "example": "C250720170000001",
            "minLength": 1,
            "maxLength": 35
          },
          "resMsg": {
            "description": "Concise response message, indicating what has happened to the request",
            "type": "string",
            "example": "Requested state created successfully"
          }
        }
      },
      "ValErrorResponse": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/Response"
          },
          {
            "type": "object",
            "description": "Error Response defining the validation failures",
            "properties": {
              "valErrors": {
                "type": "array",
                "items": {
                  "type": "object",
                  "description": "Represents details of a validation error",
                  "properties": {
                    "code": {
                      "type": "string",
                      "description": "Error code"
                    },
                    "field": {
                      "type": "string",
                      "description": "Name of the field, that has failed validation"
                    },
                    "message": {
                      "type": "string",
                      "description": "Error description"
                    }
                  }
                },
                "example": [
                  {
                    "code": "ERRMSG0001",
                    "field": "Id",
                    "message": "Mandatory id field missing."
                  },
                  {
                    "code": "ERRMSG0002",
                    "field": "Amount",
                    "message": "Amount can't be blank."
                  }
                ]
              }
            }
          }
        ]
      },
      "ReleaseRequestBody": {
        "type": "object",
        "properties": {
          "context": {
            "$ref": "#/components/schemas/Context"
          }
        },
        "example": {
          "context": {
            "channelSeqId": "C250720170000001",
            "action": "release"
          }
        }
      }
    },
    "responses": {
      "Response_200": {
        "description": "Success response indicating request Status updated successfully",
        "schema": {
          "$ref": "#/definitions/Response"
        },
        "examples": {
          "application/json": {
            "channelSeqId": "C250720170000002",
            "resMsg": "Request Status updated successfully"
          }
        }
      },
      "Response_201": {
        "description": "Success response indicating request state created successfully",
        "schema": {
          "$ref": "#/definitions/Response"
        },
        "examples": {
          "application/json": {
            "channelSeqId": "C250720170000002",
            "resMsg": "Requested state created successfully"
          }
        }
      },
      "Response_500": {
        "description": "An Error Response indicating internal server error",
        "schema": {
          "$ref": "#/definitions/Response"
        },
        "examples": {
          "application/json": {
            "channelSeqId": null,
            "resMsg": "Internal Server Error"
          }
        }
      },
      "Response_202": {
        "description": "Success response indicating acceptance of request for further processing",
        "schema": {
          "$ref": "#/definitions/Response"
        },
        "examples": {
          "application/json": {
            "channelSeqId": "C250720170000002",
            "resMsg": "Request accepted for further processing"
          }
        }
      },
      "Response_409": {
        "description": "An Error Response indicating resource conflict",
        "schema": {
          "$ref": "#/definitions/Response"
        },
        "examples": {
          "application/json": {
            "channelSeqId": "C250720170000002",
            "resMsg": "Request conflicts with present resource state"
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Wallet",
      "description": "APIs to manage Wallet catalog of different Wallet type which includes beneficiary, customer, Service Provider and administration."
    }
  ]
}