{
  "openapi": "3.0.3",
  "info": {
    "title": "KeyNest API",
    "version": "3.0.0",
    "description": "KeyNest API allows partners and clients to integrate key exchange services. This REST API enables key management, code generation, and tracking for secure key storage and exchange through KeyNest stores.",
    "contact": {
      "email": "support@keynest.com",
      "url": "https://keynest.com"
    }
  },
  "servers": [
    {
      "url": "https://api.keynest.com/api/v3",
      "description": "KeyNest API v3"
    }
  ],
  "security": [
    {
      "ApiKeyAuth": []
    }
  ],
  "paths": {
    "/KeyNests": {
      "get": {
        "summary": "List of KeyNests",
        "description": "<p>This will return the list of KeyNest locations in which the service works depending on your filter options.</p>\n<h2 id=\"header\">HEADER</h2>\n<div class=\"click-to-expand-wrapper is-table-wrapper\"><table>\n<thead>\n<tr>\n<th>Name</th>\n<th>Type</th>\n<th>Required</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>ApiKey</td>\n<td>String</td>\n<td>Yes</td>\n</tr>\n</tbody>\n</table>\n</div><h2 id=\"params\">Params</h2>\n<div class=\"click-to-expand-wrapper is-table-wrapper\"><table>\n<thead>\n<tr>\n<th>Name</th>\n<th>Type</th>\n<t",
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Invalid API key"
          },
          "404": {
            "description": "Not found"
          }
        }
      }
    },
    "/Keys/LOC01": {
      "post": {
        "summary": "New key for KeyNest Stores globally",
        "description": "<p>For adding a new key, you can use this endpoint:</p>\n<ol>\n<li><p>You will receive a dropoff code + a collection code.</p>\n</li>\n<li><p>At the first dropoff, the shopkeeper will use the dropoff code to attach one of our fobs to the key. This fob remains on the key and it allows the key to be dropped off without the need for a dropoff code for the 2nd time onwards.</p>\n</li>\n</ol>\n<p>For a key that already has a KeyNest fob attached, use the <a href=\"https://documenter.getpostman.com/view/54567",
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Invalid API key"
          },
          "404": {
            "description": "Not found"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              },
              "example": {
                "KeyName": "API Key",
                "PropertyId": "KN 123",
                "StoreId": 5,
                "ExpectedCollectionUserName": "Harry",
                "IsPermanentCode": false,
                "ValidFrom": "2019-03-13T10:37:39.9989584+05:30",
                "ValidTo": "2019-03-20T10:37:39.9989584+05:30",
                "DefaultOfficeId": 106
              }
            }
          }
        }
      }
    },
    "/Keys": {
      "get": {
        "summary": "List all my keys  ",
        "description": "<p>This endpoint return the list of all of your keys, including details of each key and their current status.</p>\n",
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Invalid API key"
          },
          "404": {
            "description": "Not found"
          }
        }
      },
      "put": {
        "summary": "Update key details",
        "description": "<p>You can use this endpoint to update your key details.  </p>\n<div class=\"click-to-expand-wrapper is-table-wrapper\"><table>\n<thead>\n<tr>\n<th>Name</th>\n<th>Type</th>\n<th>Required</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>KeyId</td>\n<td>String</td>\n<td>Yes</td>\n</tr>\n<tr>\n<td>KeyName</td>\n<td>String</td>\n<td>No</td>\n</tr>\n<tr>\n<td>Address</td>\n<td>String</td>\n<td>No</td>\n</tr>\n<tr>\n<td>PropertyId</td>\n<td>String</td>\n<td>No</td>\n</tr>\n<tr>\n<td>Notes</td>\n<td>String</td>\n<td>No</td>\n</tr>\n</tbody>\n</ta",
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Invalid API key"
          },
          "404": {
            "description": "Not found"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              },
              "example": {
                "KeyName": "Demo keys XXX",
                "Address": "27 Birnam Street",
                "PropertyId": "KN123",
                "Notes": "Guest set"
              }
            }
          }
        }
      }
    },
    "/Keys/{KeyId}": {
      "get": {
        "summary": "Get Key Status",
        "description": "<p>Use this endpoint to identify the current key status. We have three different status:</p>\n<p>-Waiting for drop off:</p>\n<p>This status means that the key has been created but it has not been dropped off before.</p>\n<p>-In Store:</p>\n<p>This status means that the key <strong>is</strong> currently in one of our KeyNest stores.</p>\n<p>-In Use:</p>\n<p>This status means that the key has been collected from one of our KeyNest stores.</p>\n",
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Invalid API key"
          },
          "404": {
            "description": "Not found"
          }
        },
        "parameters": [
          {
            "name": "KeyId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "The KeyId parameter"
          }
        ]
      },
      "delete": {
        "summary": "Delete a key",
        "description": "<p>Please use this endpoint to delete a key.</p>\n<p>For your information, it's not possible to delete keys that are stored in one of our locations. </p>\n",
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Invalid API key"
          },
          "404": {
            "description": "Not found"
          }
        },
        "parameters": [
          {
            "name": "KeyId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "The KeyId parameter"
          }
        ]
      }
    },
    "/Codes/CollectionCode/LOC01": {
      "post": {
        "summary": "Get collection code for KeyNest Stores globally",
        "description": "<p>Please use this endpoint to book a collection code.</p>\n<p>Requests without the StoreId:</p>\n<ul>\n<li>if the StoreId is not specified in request body, KeyNest will identify the Store where the key has been dropped off at the last movement and use the StoreId for the request.</li>\n</ul>\n<div class=\"click-to-expand-wrapper is-table-wrapper\"><table>\n<thead>\n<tr>\n<th>Name</th>\n<th>Type</th>\n<th>Required</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>KeyId</td>\n<td>String</td>\n<td>Yes</td>\n</tr>\n<tr>\n<td>St",
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Invalid API key"
          },
          "404": {
            "description": "Not found"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              },
              "example": {
                "KeyId": "6296065649153519",
                "StoreId": 5,
                "ExpectedCollectionUserName": "",
                "IsPermanentCode": false,
                "ValidFrom": "",
                "ValidTo": ""
              }
            }
          }
        }
      }
    },
    "/SingleKeyExchange": {
      "post": {
        "summary": "Single Key Exchange",
        "description": "<p>When adding a key using this endpoint, you will receive a drop-off code + a collection code. </p>\n<h2 id=\"keynest-stores\">KeyNest Stores</h2>\n<ul>\n<li><p>if you\u2019re dropping off your keys at one of our regular stores, the staff will enter the drop-off code and attach one of our fobs. The keys will then be scanned and stored securely.</p>\n</li>\n<li><p>Anyone can then collect the key by sharing the collection code with the staff at our KeyNest store.</p>\n</li>\n</ul>\n<h2 id=\"lockers-in-the-uk-and",
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Invalid API key"
          },
          "404": {
            "description": "Not found"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        }
      }
    },
    "/SingleKeyExchange/NextPair": {
      "post": {
        "summary": "Next Pair - Single Key Exchange",
        "description": "<p>Once the key has been created using the Single Key Exchange endpoint, this endpoint allows you to retrieve the next codes that can be used to collect it / drop it off.</p>\n<p>There are three possible situations</p>\n<ul>\n<li><p>If the key has never been dropped off yet, this endpoint will return the same two codes already displayed on the Single Key Exchange endpoint.</p>\n</li>\n<li><p>If the key is already stored in the locker, this endpoint will return one code: the next collection code.</p>\n",
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Invalid API key"
          },
          "404": {
            "description": "Not found"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              },
              "example": {
                "KeyId": "E62C22EC88220E6B",
                "StoreId": 2015
              }
            }
          }
        }
      }
    },
    "/Codes/DropOffCode/{KeyId}": {
      "get": {
        "summary": "Retrieve drop off code",
        "description": "<p>This endpoint will return the drop off code for a specific key which has already been created in KeyNest.</p>\n",
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Invalid API key"
          },
          "404": {
            "description": "Not found"
          }
        },
        "parameters": [
          {
            "name": "KeyId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "The KeyId parameter"
          }
        ]
      }
    },
    "/Codes/CollectionCode": {
      "get": {
        "summary": "Get collection code Status",
        "description": "<p>Please use this endpoint to find out if a code is valid or not.</p>\n",
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Invalid API key"
          },
          "404": {
            "description": "Not found"
          }
        }
      }
    },
    "/Codes/CollectionCode/{CollectionCode}": {
      "delete": {
        "summary": "Delete collection code",
        "description": "<p>Please use this endpoint to delete a collection code.</p>\n",
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Invalid API key"
          },
          "404": {
            "description": "Not found"
          }
        },
        "parameters": [
          {
            "name": "CollectionCode",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "The CollectionCode parameter"
          }
        ]
      }
    },
    "/MyOffices": {
      "get": {
        "summary": "List of my offices",
        "description": "<p>This endpoint return the list of all of your offices.</p>\n<div class=\"click-to-expand-wrapper is-table-wrapper\"><table>\n<thead>\n<tr>\n<th>Name</th>\n<th>Type</th>\n<th>Required</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>ApiKey</td>\n<td>String</td>\n<td>Yes</td>\n</tr>\n</tbody>\n</table>\n</div>",
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Invalid API key"
          },
          "404": {
            "description": "Not found"
          }
        }
      }
    },
    "/Codes/ShareCode": {
      "post": {
        "summary": "Share codes via email",
        "description": "<p>You can use this endpoint if you want KeyNest to send the drop-off or collection information to someone.</p>\n<div class=\"click-to-expand-wrapper is-table-wrapper\"><table>\n<thead>\n<tr>\n<th>Name</th>\n<th>Type</th>\n<th>Required</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>CodeType</td>\n<td>String</td>\n<td>Yes</td>\n</tr>\n<tr>\n<td>Code</td>\n<td>String</td>\n<td>Yes</td>\n</tr>\n<tr>\n<td>Email</td>\n<td>String</td>\n<td>Yes</td>\n</tr>\n</tbody>\n</table>\n</div><p>The options for CodeType are \"DropOff\" or \"Collect",
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Invalid API key"
          },
          "404": {
            "description": "Not found"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              },
              "example": {
                "CodeType": "Drop-Off",
                "Code": "909919",
                "Email": "lucas@keynest.com"
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "ApiKeyAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "ApiKey",
        "description": "API Key for authentication. Get your API key from your profile section at secure.keynest.com"
      }
    },
    "schemas": {
      "Key": {
        "type": "object",
        "properties": {
          "KeyId": {
            "type": "string",
            "description": "Unique identifier for the key"
          },
          "Status": {
            "type": "string",
            "description": "Current status of the key"
          }
        }
      },
      "CollectionCode": {
        "type": "object",
        "properties": {
          "Code": {
            "type": "string",
            "description": "Collection code"
          },
          "ExpiryDate": {
            "type": "string",
            "format": "date-time",
            "description": "When the code expires"
          }
        }
      }
    }
  }
}