{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.2",
    "title": "All member gateway inquiry profile",
    "description": "All member gateway inquiry profile",
    "x-jentic-source-url": "https://api.swaggerhub.com/apis/onlgs/all_member_gateway_inquiry_profile/1.0.2/swagger.json",
    "contact": {}
  },
  "servers": [
    {
      "description": "Allmember inquiry profile",
      "url": "https://asa2y2br9i.execute-api.ap-southeast-1.amazonaws.com/{environment}",
      "variables": {
        "environment": {
          "default": "staging",
          "enum": [
            "dev",
            "staging"
          ]
        }
      }
    }
  ],
  "paths": {
    "/allmember/member/profile/inquiry": {
      "post": {
        "tags": [
          "Inquiry Profile"
        ],
        "operationId": "Inquiry-profile",
        "description": "Provided member profile\n",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "sys_date_time",
                  "channel_id",
                  "identify_id",
                  "identify_value"
                ],
                "properties": {
                  "sys_date_time": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2020-07-29 10:52:00"
                  },
                  "channel_id": {
                    "type": "string",
                    "example": "CN13"
                  },
                  "identify_id": {
                    "type": "string",
                    "example": "0"
                  },
                  "identify_value": {
                    "type": "string",
                    "example": "010100005509"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "object",
                      "properties": {
                        "code": {
                          "type": "string",
                          "example": "00000"
                        },
                        "message_en": {
                          "type": "string",
                          "example": "Success"
                        },
                        "message_th": {
                          "type": "string",
                          "example": "ทำรายการสำเร็จ"
                        }
                      }
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "member_id": {
                          "type": "string",
                          "example": "010100085505"
                        },
                        "mobile_no": {
                          "type": "string",
                          "example": "0969349871"
                        },
                        "iden_no": {
                          "type": "string",
                          "example": "1640700014619"
                        },
                        "prefix_th": {
                          "type": "string",
                          "example": "น.ส."
                        },
                        "firstname_th": {
                          "type": "string",
                          "example": "ศิริญญา"
                        },
                        "lastname_th": {
                          "type": "string",
                          "example": "รู้ธรรม"
                        },
                        "iden_addr": {
                          "type": "object",
                          "properties": {
                            "address": {
                              "type": "string",
                              "example": "106/24 หมู่ที่ 6"
                            },
                            "sub_district": {
                              "type": "string",
                              "example": "สหกรณ์นิคม"
                            },
                            "district": {
                              "type": "string",
                              "example": "ทองผาภูมิ"
                            },
                            "province": {
                              "type": "string",
                              "example": "กาญจนบุรี"
                            },
                            "post_code": {
                              "type": "string",
                              "example": "71180"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Error invalid request data",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "object",
                      "properties": {
                        "code": {
                          "type": "string"
                        },
                        "message_en": {
                          "type": "string"
                        },
                        "message_th": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "invalid_data": {
                    "summary": "Invalid data",
                    "value": {
                      "error": {
                        "code": "71001",
                        "message_en": "Invalid Data",
                        "message_th": "ข้อมูลไม่ครบถ้วน กรุณากรอกใหม่อีกครั้ง"
                      }
                    }
                  },
                  "member_not_found": {
                    "summary": "Member not found",
                    "value": {
                      "error": {
                        "code": "74001",
                        "message_en": "Member Not Found",
                        "message_th": "ไม่พบข้อมูลสสมาชิก ในระบบ All Member"
                      }
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Error response from system",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "object",
                      "properties": {
                        "code": {
                          "type": "string"
                        },
                        "message_en": {
                          "type": "string"
                        },
                        "message_th": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "database_error": {
                    "summary": "Database error",
                    "value": {
                      "error": {
                        "code": "71007",
                        "message_en": "Database error",
                        "message_th": "ขออภัยในความไม่สะดวก ขณะนี้ระบบขัดข้อง กรุณาลองใหม่ภายหลัง"
                      }
                    }
                  },
                  "internal_error": {
                    "summary": "Internal server error",
                    "value": {
                      "error": {
                        "code": "79999",
                        "message_en": "Internal server error",
                        "message_th": "ขออภัยในความไม่สะดวก ขณะนี้ระบบขัดข้อง กรุณาลองใหม่ภายหลัง"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "ApiKeyAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "x-api-key"
      }
    }
  },
  "security": [
    {
      "ApiKeyAuth": []
    }
  ],
  "tags": [
    {
      "name": "Inquiry Profile"
    }
  ]
}