{
  "openapi": "3.0.0",
  "info": {
    "version": "5.0.0",
    "title": "av_microservice_gatekeeper",
    "description": "**Release Notes**\n\n |Version|  Detail|\n |---|---|\n |5.0.21  |Logging issues fixed when logging all even though set to error.  |\n |5.0.12  |Addition of UI endpoints.  |\n |5.0.9  |Upgraded to Java 17.  |\n |4.0.8  |Upgraded to Java 11 and containerised. Added /authorize endpoint.  |\n \n **Introduction**\n \n This microservice acts as a central gatekeeper for calls coming in from a variety of channels. This microservice is used in conjunction with HAProxy.\n\n If a call from a channel comes in, HAProxy will first do a check to see if the service is currently up and running before forwarding the call to the relevant microservice.\n \n **Caching is also available on the /getMode endpoint and can be set to a certain amount of seconds. This should not be 0 especially not on large sites. Please ensure that the seconds are set in the setting table of the microservice. -> CACHE_LIVENESS_SECONDS**  ",
    "x-jentic-source-url": "https://api.swaggerhub.com/apis/airvantage-team/av_microservice_gatekeeper/5.0.0/swagger.json"
  },
  "paths": {
    "/getMode": {
      "get": {
        "operationId": "GET_getMode",
        "summary": "This endpoint is used to retrieve the current maintenace mode.",
        "tags": [
          "Private"
        ],
        "description": "This endpoint will retrieve the current maintenance mode as is in the settings table of av_microservice_gatekeeper. \n\nA call to this endpoind, for example: \nhttp://localhost:8081/av_microservice_gatekeeper/getMode\n\n<b>Please note, that if the maintenance mode is disabled it will return a responseCode of \"01\" in the response.</b>\n\n<b>Please note, that if the maintenance mode is enabled it will return a responseCode of \"02\" in the response.</b>\n\n\n<p style=\"color:red\"><b>Please also note, that we can enable Caching on this endpoint!</b></p>",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "object",
                      "properties": {
                        "status": {
                          "type": "boolean"
                        },
                        "comment": {
                          "type": "string"
                        },
                        "responseCode": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "Enabled": {
                    "value": {
                      "success": true,
                      "detail": {
                        "comment": "Central maintenance mode is currently enabled.",
                        "responseCode": "01",
                        "displayMessage": "The service is currently unavailable."
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/setMode": {
      "get": {
        "operationId": "GET_setMode",
        "summary": "This endpoint is used to set the maintenance mode.",
        "tags": [
          "Private"
        ],
        "description": "This endpoint allows one to set the maintenance mode to either be disabled or enabled. \n\nTo disable maintenance mode a parameter of 0 will need to be passed, for example: \nhttp://localhost:8081/av_microservice_gatekeeper/setMode?mode=0\n\nTo enable maintenance mode a parameter of 1 will need to be passed, for example: \nhttp://localhost:8081/av_microservice_gatekeeper/setMode?mode=1",
        "parameters": [
          {
            "name": "mode",
            "in": "query",
            "description": "This will either disable (0) or enable (1) maintenance mode. ",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "displayMessage",
            "in": "query",
            "description": "One is able to set the message that will be displayed when the system is currently in maintenance mode, for example, on the USSD the message that will be displayed can either be set in the settings table of this microservice or by using this parameter. ",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "object",
                      "properties": {
                        "status": {
                          "type": "boolean"
                        },
                        "comment": {
                          "type": "string"
                        },
                        "responseCode": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "Updated": {
                    "value": {
                      "success": true,
                      "detail": {
                        "comment": "Central maintenance mode has been updated.",
                        "responseCode": "01",
                        "displayMessage": "The service is currently unavailable."
                      }
                    }
                  },
                  "Validation error": {
                    "value": {
                      "success": true,
                      "detail": {
                        "message": "Invalid parameter for mode.",
                        "responseCode": "03"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/authorize": {
      "post": {
        "operationId": "POST_authorize",
        "summary": "This endpoint is used to authorize a client/internal call and then send a JSON webservice token which can be used on other calls.",
        "tags": [
          "Private"
        ],
        "description": "This endpoint will generate a JSON webservice token which is passed back to the client/internal service and is then verified by the service or endpoint called next.",
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "user": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "Success": {
                  "value": {
                    "user": "test",
                    "password": "testpass"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "object",
                      "properties": {
                        "status": {
                          "type": "boolean"
                        },
                        "message": {
                          "type": "string"
                        },
                        "responseCode": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "Authorization token generated": {
                    "value": {
                      "success": true,
                      "detail": {
                        "message": "Successful generation of authorization token.",
                        "responseCode": "01",
                        "authToken": "eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJpZCIsImlhdCI6MTY0MjA2MTg2NSwic3ViIjoidGVzdEVuZHBvaW50IiwiaXNzIjoiQWlydmFudGFnZSIsImV4cCI6MzI4NDEyMzczMX0.uwek3rx4zPf6m3DP7Re8YksCbZM8GxZXozV9nwri71Q"
                      }
                    }
                  },
                  "Validation failure": {
                    "value": {
                      "success": true,
                      "detail": {
                        "message": "Missing parameter for password, please ensure parameters are correct.",
                        "responseCode": "03"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/addUser": {
      "post": {
        "operationId": "POST_adduser",
        "summary": "This endpoint is used to add a user to the database who might need to use JSON Webservice Tokens.",
        "tags": [
          "UI"
        ],
        "description": "This endpoint will be used to add a user to the database. Please note that the Authentication key should be passed in the request header and the admin JWT that was created should also be passed as the value. \n\nFor example: \n\nAuthentication: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJpZCIsImlhdCI6MTY3OTU3NDkwMiwic3ViIjoiYWRtaW5pc3RyYXRvciIsImlzcyI6IkFpcnZhbnRhZ2UiLCJleHAiOjMzNTkxNDk4MDN9.NHE6osJIm9TDBWwWOFtM3F_FRdG8Le0t2J5pgYNLBqI",
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "user": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "role": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "Success": {
                  "value": {
                    "user": "test",
                    "password": "testpass",
                    "role": "tester"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "object",
                      "properties": {
                        "status": {
                          "type": "boolean"
                        },
                        "message": {
                          "type": "string"
                        },
                        "responseCode": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "User added successfully": {
                    "value": {
                      "success": true,
                      "detail": {
                        "message": "User added successfully.",
                        "responseCode": "01"
                      }
                    }
                  },
                  "Validation failure": {
                    "value": {
                      "success": true,
                      "detail": {
                        "message": "Missing parameter for user, please ensure parameters are correct.",
                        "responseCode": "03"
                      }
                    }
                  },
                  "User already exists": {
                    "value": {
                      "success": true,
                      "detail": {
                        "message": "User already exists.",
                        "responseCode": "04"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/getUserInfo": {
      "get": {
        "operationId": "GET_userInfo",
        "summary": "This endpoint is used to retrieve the role and other data for a user.",
        "tags": [
          "UI"
        ],
        "description": "This endpoint will be used to retrieve the user information. Please note that the Authentication key should be passed in the request header and the JWT that was created should also be passed as the value. \n\nFor example: \n\nAuthentication: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJpZCIsImlhdCI6MTY3OTU3NDkwMiwic3ViIjoiYWRtaW5pc3RyYXRvciIsImlzcyI6IkFpcnZhbnRhZ2UiLCJleHAiOjMzNTkxNDk4MDN9.NHE6osJIm9TDBWwWOFtM3F_FRdG8Le0t2J5pgYNLBqI",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "object",
                      "properties": {
                        "status": {
                          "type": "boolean"
                        },
                        "message": {
                          "type": "string"
                        },
                        "responseCode": {
                          "type": "string"
                        },
                        "username": {
                          "type": "string"
                        },
                        "role": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "User info successfully retrieved": {
                    "value": {
                      "success": true,
                      "detail": {
                        "message": "User info successfully retrieved.",
                        "responseCode": "01",
                        "username": "awesometester",
                        "role": "Tester"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/getUsers": {
      "get": {
        "operationId": "GET_users",
        "summary": "This endpoint is used to retrieve the user(s) list.",
        "tags": [
          "UI"
        ],
        "description": "This endpoint will be used to retrieve the users list. Please note that the Authentication key should be passed in the request header and the JWT that was created should also be passed as the value. \n\nFor example: \n\nAuthentication: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJpZCIsImlhdCI6MTY3OTU3NDkwMiwic3ViIjoiYWRtaW5pc3RyYXRvciIsImlzcyI6IkFpcnZhbnRhZ2UiLCJleHAiOjMzNTkxNDk4MDN9.NHE6osJIm9TDBWwWOFtM3F_FRdG8Le0t2J5pgYNLBqI",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "object",
                      "properties": {
                        "status": {
                          "type": "boolean"
                        },
                        "message": {
                          "type": "string"
                        },
                        "users": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "username": {
                                "type": "string"
                              },
                              "role": {
                                "type": "string"
                              }
                            }
                          }
                        },
                        "responseCode": {
                          "type": "string"
                        },
                        "username": {
                          "type": "string"
                        },
                        "role": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "User info successfully retrieved": {
                    "value": {
                      "success": true,
                      "detail": {
                        "message": "Users list successfully retrieved.",
                        "users": [
                          {
                            "id": 1,
                            "username": "awesometester",
                            "role": "Tester"
                          },
                          {
                            "id": 2,
                            "username": "DevOps",
                            "role": "Admin"
                          },
                          {
                            "id": 3,
                            "username": "customercare",
                            "role": "Tester"
                          }
                        ],
                        "responseCode": "01"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/modifyRole": {
      "post": {
        "operationId": "POST_modifyRole",
        "summary": "This endpoint is used to modify the role of a user.",
        "tags": [
          "UI"
        ],
        "description": "This endpoint will be used to modify the role/subject of a user. Please note that the Authentication key should be passed in the request header and the admin JWT that was created should also be passed as the value. \n\nFor example: \n\nAuthentication: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJpZCIsImlhdCI6MTY3OTU3NDkwMiwic3ViIjoiYWRtaW5pc3RyYXRvciIsImlzcyI6IkFpcnZhbnRhZ2UiLCJleHAiOjMzNTkxNDk4MDN9.NHE6osJIm9TDBWwWOFtM3F_FRdG8Le0t2J5pgYNLBqI",
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "user": {
                    "type": "string"
                  },
                  "role": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "Success": {
                  "value": {
                    "user": "test",
                    "role": "tester"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "object",
                      "properties": {
                        "status": {
                          "type": "boolean"
                        },
                        "message": {
                          "type": "string"
                        },
                        "responseCode": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "User modified successfully": {
                    "value": {
                      "success": true,
                      "detail": {
                        "message": "User successfully modified.",
                        "responseCode": "01"
                      }
                    }
                  },
                  "Validation failure": {
                    "value": {
                      "success": true,
                      "detail": {
                        "message": "Missing parameter for role, please ensure parameters are correct.",
                        "responseCode": "03"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/resetPassword": {
      "post": {
        "operationId": "POST_resetPassword",
        "summary": "This endpoint is used to modify an existing user's password.",
        "tags": [
          "UI"
        ],
        "description": "This endpoint will be used to modify an existing user's password on AV's side by setting up a new password for the user/client. \n\n\n Please note that the Authentication key should be passed in the request header and the admin JWT that was created should also be passed as the value.\n\nFor example: \n\nAuthentication: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJpZCIsImlhdCI6MTY3OTU3NDkwMiwic3ViIjoiYWRtaW5pc3RyYXRvciIsImlzcyI6IkFpcnZhbnRhZ2UiLCJleHAiOjMzNTkxNDk4MDN9.NHE6osJIm9TDBWwWOFtM3F_FRdG8Le0t2J5pgYNLBqI",
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "user": {
                    "type": "string"
                  },
                  "oldPassword": {
                    "type": "string"
                  },
                  "newPassword": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "Success": {
                  "value": {
                    "user": "test",
                    "oldPassword": "oldPasswordTester",
                    "newPassword": "newPasswordTester"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "object",
                      "properties": {
                        "status": {
                          "type": "boolean"
                        },
                        "message": {
                          "type": "string"
                        },
                        "responseCode": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "User password reset successful": {
                    "value": {
                      "success": true,
                      "detail": {
                        "message": "Password for user: testUser successfully updated.",
                        "responseCode": "01"
                      }
                    }
                  },
                  "Validation failure": {
                    "value": {
                      "success": true,
                      "detail": {
                        "message": "Missing parameter for user, please ensure parameters are correct.",
                        "responseCode": "03"
                      }
                    }
                  },
                  "Failure to verify user": {
                    "value": {
                      "success": true,
                      "detail": {
                        "message": "Failed to verify the user.",
                        "responseCode": "03"
                      }
                    }
                  },
                  "Failure to authenticate user": {
                    "value": {
                      "success": true,
                      "detail": {
                        "message": "Failed to authenticate the user passed, please ensure correct password was passed.",
                        "responseCode": "03"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/getStatus": {
      "$ref": "https://api.swaggerhub.com/domains/airvantage-team/AVCommons/3.0.0#/components/pathitems/GetStatus"
    },
    "/reloadSettings": {
      "get": {
        "operationId": "GET_reloadSettings",
        "summary": "This endpoint can be used to reload the settings in the database.",
        "tags": [
          "Basic"
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "object",
                      "properties": {
                        "status": {
                          "type": "boolean"
                        },
                        "message": {
                          "type": "string"
                        },
                        "responseCode": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "Success": {
                    "value": {
                      "success": true,
                      "detail": {
                        "message": "Success",
                        "responseCode": "01"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Private"
    }
  ],
  "components": {
    "parameters": {
      "trait_queryParamActiondate_actionDate": {
        "name": "actionDate",
        "in": "query",
        "description": "Used to represent event Dates",
        "required": true,
        "schema": {
          "type": "string",
          "format": "date"
        }
      },
      "trait_queryParamAdvanceid_advanceId": {
        "name": "advanceId",
        "in": "query",
        "description": "Unique identifier of new Advance (/addAdvance) or which advance to repay (/addRepayment)",
        "required": true,
        "schema": {
          "type": "string"
        }
      },
      "trait_queryParamLoanamount_loanAmt": {
        "name": "loanAmt",
        "in": "query",
        "description": "Amount borrowed by subscriber OR\nAmount being allocated to repaying the Loan (/addRepayment)",
        "required": true,
        "schema": {
          "type": "number"
        }
      },
      "trait_queryParamDenomlistid_denomListId": {
        "name": "denomListId",
        "in": "query",
        "description": "Which list of denominations should be displayed?  ",
        "required": true,
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 3,
          "default": 1
        }
      },
      "trait_queryParamEntitytype_entityType": {
        "name": "entityType",
        "in": "query",
        "description": "1. MoMo\n2. Airtime\n3. Data",
        "required": true,
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 3,
          "default": 2
        }
      },
      "trait_queryParamLoandate_loanDate": {
        "name": "loanDate",
        "in": "query",
        "description": "Timestamp of loan taken\nyyyy/mm/dd HH:mm:ss",
        "schema": {
          "type": "string"
        }
      },
      "trait_queryParamMsisdn_msisdn": {
        "name": "msisdn",
        "in": "query",
        "required": true,
        "schema": {
          "type": "string",
          "minLength": 8,
          "maxLength": 13
        }
      },
      "trait_queryParamProfiletierid_profileTierId": {
        "name": "profileTierId",
        "in": "query",
        "required": true,
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 999
        }
      },
      "trait_queryParamRechargeamt_rechargeAmt": {
        "name": "rechargeAmt",
        "in": "query",
        "description": "Amount being recharged ",
        "required": true,
        "schema": {
          "type": "number"
        }
      },
      "trait_queryParamRechargedate_rechargeDate": {
        "name": "rechargeDate",
        "in": "query",
        "description": "Timestamp of recharge\nyyyy/mm/dd HH:mm:ss",
        "schema": {
          "type": "string"
        }
      },
      "trait_queryParamReconcilesource_source": {
        "name": "source",
        "in": "query",
        "description": "1 - CDR\n2 - Daily/Periodical Recon Task",
        "schema": {
          "type": "integer",
          "default": 1
        }
      },
      "trait_queryParamRepaydate_repayDate": {
        "name": "repayDate",
        "in": "query",
        "description": "Timestamp of loan repaid\nyyyy/mm/dd HH:mm:ss",
        "schema": {
          "type": "string"
        }
      },
      "trait_queryParamServiceamt_serviceAmt": {
        "name": "serviceAmt",
        "in": "query",
        "description": "Amount being allocated to the service fee",
        "required": true,
        "schema": {
          "type": "number"
        }
      },
      "trait_queryParamServiceid_serviceId": {
        "name": "serviceId",
        "in": "query",
        "description": "This is the service ID which will indicate </br>1 - Airtime Once-off; </br>2 - Airtime Auto_Topup and </br>3 - Data",
        "schema": {
          "type": "string"
        }
      },
      "trait_queryParamStatusid_statusId": {
        "name": "statusId",
        "in": "query",
        "description": "2 - Confirmed advance/payment\n3 - Cancelled advance/payment\n6 -  Queued advance/payment",
        "required": true,
        "schema": {
          "type": "integer",
          "enum": [
            2,
            3,
            6
          ]
        }
      },
      "trait_queryParamTimestamp_timestamp": {
        "name": "timestamp",
        "in": "query",
        "description": "Timestamp of the event, comprising Date AND Time.\nE.g. 2016/09/02 11:10:02",
        "required": true,
        "schema": {
          "type": "string",
          "format": "date-time"
        }
      }
    }
  },
  "servers": [
    {
      "description": "SwaggerHub API Auto Mocking",
      "url": "https://virtserver.swaggerhub.com/airvantage-team/av_microservice_gatekeeper/3.0.0"
    }
  ]
}