{
  "openapi": "3.0.3",
  "info": {
    "title": "RallyUp REST API",
    "version": "2.0.0",
    "description": "RallyUp's REST API provides two basic functionalities: (1) Giving organizations easy access to their data in RallyUp to integrate with other data sources and data management software, and (2) Giving partners the ability to integrate basic functionalities of RallyUp within their own software.",
    "x-jentic-source-url": "https://api.rallyup.com"
  },
  "servers": [
    {
      "url": "https://go.rallyup.com"
    }
  ],
  "tags": [
    {
      "name": "Authentication",
      "description": "Token-based authentication endpoints"
    },
    {
      "name": "System",
      "description": "System and version endpoints"
    },
    {
      "name": "Users",
      "description": "User management endpoints"
    },
    {
      "name": "Campaigns",
      "description": "Campaign management endpoints"
    },
    {
      "name": "Donations",
      "description": "Donation and transaction endpoints"
    },
    {
      "name": "Auctions",
      "description": "Auction-related endpoints"
    },
    {
      "name": "Raffles & Sweepstakes",
      "description": "Raffle and sweepstakes endpoints"
    },
    {
      "name": "Activities",
      "description": "Activity and participation endpoints"
    },
    {
      "name": "Communication",
      "description": "Messaging endpoints"
    },
    {
      "name": "Streaming",
      "description": "Live streaming endpoints"
    }
  ],
  "paths": {
    "/v1/token": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "/v1/token",
        "operationId": "postToken",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "description": "Retrieve an authorization token to be passed for authentication in other API calls",
        "parameters": [
          {
            "name": "user-email",
            "in": "header",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "If specified, this user will be identified with the authorization token and set as the author of any API calls made with the token"
          },
          {
            "name": "user-password",
            "in": "header",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "The password to the user's RallyUp account. Required if user-email is specified."
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "type": "object",
                "properties": {
                  "grant_type": {
                    "type": "string",
                    "description": "Required grant_type for authorization"
                  },
                  "username": {
                    "type": "string",
                    "description": "Your organization's login user name received from your organizational api credentials"
                  },
                  "password": {
                    "type": "string",
                    "description": "Your organization's api secret from your organizational api credentials. We recommend that this isn't hard-coded into your api calls when retrieving a new token."
                  }
                },
                "required": [
                  "grant_type",
                  "username",
                  "password"
                ]
              }
            }
          }
        },
        "security": []
      }
    },
    "/v2/api/version": {
      "get": {
        "tags": [
          "System"
        ],
        "summary": "/v2/api/version",
        "operationId": "getVersion",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "Result": {
                    "Version": "1.0.0",
                    "ReleasedAt": "2018/03/13 00:00:00",
                    "IdentityType": "RallyUpIdentity",
                    "UserName": "ab4333e7-648b-4294-a45c-baf5fd24edf9",
                    "AuthenticationType": "ExternalBearer",
                    "IsAuthenticated": true,
                    "Name": "ab4333e7-648b-4294-a45c-baf5fd24edf9",
                    "Roles": [
                      "ApiUser"
                    ]
                  },
                  "Ok": true,
                  "Error": null,
                  "Metadata": {}
                }
              }
            }
          }
        },
        "description": "Check the authorization and version of the API"
      }
    },
    "/v2/api/finduser/{user_email}": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "/v2/api/finduser/{user_email}",
        "operationId": "getFinduserUser_email",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "Result": {
                    "Addresses": null,
                    "CreatedDate": "2017/08/08 17:47:33",
                    "UpdatedDate": "2018/03/19 21:23:46",
                    "IsInactive": false,
                    "HasPassword": true,
                    "UserId": 4968,
                    "Email": "jimmy@rallyup.com",
                    "FirstName": "Jimmy",
                    "LastName": "Yao",
                    "Phone": null
                  },
                  "Ok": true,
                  "Error": null,
                  "Metadata": {}
                }
              }
            }
          }
        },
        "description": "Find and retrieve information on a RallyUp user by their email address",
        "parameters": [
          {
            "name": "user_email",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ]
      }
    },
    "/v2/api/campaign/{campaignId}": {
      "get": {
        "tags": [
          "Campaigns"
        ],
        "summary": "/v2/api/campaign/{campaignId}",
        "operationId": "getCampaignCampaignid",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "Result": {
                    "Id": 1144,
                    "Name": "Sale for API",
                    "Url": "https://go.rallyup.com/eae009",
                    "CampaignSetupUrl": "https://go.rallyup.com/Campaigns/Setup/eae009",
                    "CampaignStatus": "Started",
                    "StartDateUtc": "2018/03/27 17:07:44",
                    "EndDateUtc": "2018/09/28 07:59:00",
                    "AmountRaised": 100,
                    "AmountRaisedInPeriod": 0,
                    "AmountGoal": 100,
                    "GoalPeriod": null,
                    "TotalViews": 1,
                    "TotalSupporters": 1,
                    "ImageURL": "https://s3.amazonaws.com/rallyup-campaigns/1234321.jpg"
                  },
                  "Ok": true,
                  "Error": null,
                  "Metadata": {}
                }
              }
            }
          }
        },
        "description": "Retreieve a campaign in RallyUp by its ID",
        "parameters": [
          {
            "name": "campaignId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ]
      }
    },
    "/v2/api/listcampaigns": {
      "get": {
        "tags": [
          "Campaigns"
        ],
        "summary": "/v2/api/listcampaigns",
        "operationId": "getListcampaigns",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "description": "Retrieve a list of all campaigns that your organization is running in RallyUp"
      }
    },
    "/v2/api/listdonations": {
      "get": {
        "tags": [
          "Donations"
        ],
        "summary": "/v2/api/listdonations",
        "operationId": "getListdonations",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "Result": {
                    "Items": [
                      {
                        "CampaignId": 1144,
                        "IsRecurring": false,
                        "CampaignName": "Sale for API",
                        "CampaignType": "Sale",
                        "Status": "Paid",
                        "PaymentType": "CreditCard",
                        "CreditCardLast4": "4242",
                        "CreditCardType": "Visa",
                        "Source": "RallyUp",
                        "FundCode": null,
                        "AgreementInfo": "not provided",
                        "SpecialInstructions": null,
                        "Causes": [],
                        "CustomFields": [],
                        "Items": [
                          {
                            "ItemId": 47,
                            "Name": "Item Number 1",
                            "Quantity": 4,
                            "Type": "SaleItem",
                            "Price": 15
                          },
                          {
                            "ItemId": 48,
                            "Name": "Item Number 2",
                            "Quantity": 2,
                            "Type": "SaleItem",
                            "Price": 20
                          }
                        ],
                        "RecurrencePeriod": null,
                        "IsRefunded": false,
                        "RefundReason": null,
                        "RefundDate": null,
                        "RecurringEndDate": null,
                        "TransactionId": 989,
                        "TransactionCreatedDate": "2018/03/27 17:11:45",
                        "TransactionUpdatedDate": "2018/03/27 17:11:47",
                        "TransactionGrossAmount": "$101.00",
                        "TransactionNetAmount": "$93.77",
                        "AthonAmount": null,
                        "AuctionAmount": null,
                        "CrowdfundingAmount": null,
                        "TicketingAmount": null,
                        "RaffleAmount": null,
                        "SaleAmount": 35,
                        "SweepstakesAmount": null,
                        "GeneralDonationAmount": null,
                        "AthonFee": null,
                        "AuctionFee": null,
                        "CrowdfundingFee": null,
                        "TicketingFee": null,
                        "RaffleFee": null,
                        "SaleFee": null,
                        "SweepstakesFee": null,
                        "GeneralDonationFee": null,
                        "NetDeductibleAmount": 93.77,
                        "MailingAddress": {
                          "MailingFirstName": "Jimmy",
                          "MailingLastName": "Yao",
                          "Address1": "7650 E. Broadway Blvd",
                          "Address2": "Suite 203",
                          "City": "Tucson",
                          "State": "AZ",
                          "Country": "United States",
                          "ZipCode": "85710",
                          "Phone": "5205555555"
                        },
                        "Members": [],
                        "FeesPaidBySupporters": null,
                        "Comment": null,
                        "RecievedEmailCampaignUpdates": true,
                        "DonorId": 3,
                        "DonorEmail": "support@rallyup.com",
                        "DonorLastName": "Yao",
                        "DonorFirstName": "Jimmy"
                      }
                    ],
                    "Count": 1,
                    "PageIndex": 1,
                    "PageSize": 100,
                    "TotalCount": 1,
                    "TotalPages": 1,
                    "HasPreviousPage": false,
                    "HasNextPage": false
                  },
                  "Ok": true,
                  "Error": null,
                  "Metadata": {}
                }
              }
            }
          }
        },
        "description": "Retrieve a paginated list of all donations made to your organization"
      }
    },
    "/v3/api/transactionItems": {
      "get": {
        "tags": [
          "Donations"
        ],
        "summary": "/v3/api/transactionItems/{campaignType}",
        "operationId": "getTransactionitems",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "id": 25822,
                  "CampaignID": 329,
                  "CampaignTitle": "My Campaign",
                  "FirstName": "FirstName",
                  "LastName": "LastName",
                  "Email": "email@email.com",
                  "Date": "2020-12-17T11:32:31.763Z",
                  "Currency": "USD",
                  "CurrencySymbol": "$",
                  "Members": [],
                  "IsAnonymous": true,
                  "InNameOf": null,
                  "MarketingOptIn": false,
                  "MailingAddress": {
                    "MailingFirstName": "FirstName",
                    "MailingLastName": "LastName",
                    "Address1": "AddressLine1",
                    "Address2": null,
                    "City": "City",
                    "State": "AK",
                    "Country": "United States",
                    "ZipCode": "630090",
                    "Phone": null
                  },
                  "GiftAidOptIn": false,
                  "GiftAidInformation": null,
                  "FundCode": null,
                  "SpecialInstructions": null,
                  "Causes": [],
                  "CustomFields": [],
                  "Comment": null,
                  "ReceivedEmailCampaignUpdates": true,
                  "DonorId": 1,
                  "RaffleTickets": [
                    {
                      "Amount": 50,
                      "EntryStartNumber": 11,
                      "EntryEndNumber": 20,
                      "EntryLevel": null,
                      "Quantity": 10,
                      "Prize": null,
                      "Type": "Online Tickets"
                    },
                    {
                      "Amount": 50,
                      "EntryStartNumber": 4,
                      "EntryEndNumber": 8,
                      "EntryLevel": null,
                      "Quantity": 5,
                      "Prize": null,
                      "Type": "Online Tickets"
                    }
                  ],
                  "SweepstakesEntries": null,
                  "AThonPledges": null,
                  "EventTickets": null,
                  "CrowdfundingPerks": null,
                  "SaleItems": null,
                  "CampaignFriendlyURL": "https://go.rallyup.com/mycampaign",
                  "CampaignPermanentURL": "https://go.rallyup.com/xxxxxx",
                  "DateFormatted": "12/17/2020 3:32AM PST"
                }
              }
            }
          }
        },
        "description": "Returns a list of objects that provide information on the items purchased on transactions"
      }
    },
    "/v3/api/auctionBids": {
      "get": {
        "tags": [
          "Auctions"
        ],
        "summary": "/v3/api/auctionBids",
        "operationId": "getAuctionbids",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": [
                  {
                    "id": "E_564156",
                    "CampaignID": 110982,
                    "CampaignTitle": "An Auction Fundraiser",
                    "FirstName": "Jimmy",
                    "LastName": "Yao",
                    "Email": "email@email.com",
                    "Date": "2021-03-25T22:39:57.513Z",
                    "DateFormatted": "3/25/2021 6:39PM EST",
                    "Currency": "USD",
                    "CurrencySymbol": "$",
                    "Members": [],
                    "IsAnonymous": false,
                    "InNameOf": null,
                    "MarketingOptIn": false,
                    "MailingAddress": null,
                    "GiftAidOptIn": false,
                    "GiftAidInformation": null,
                    "FundCode": null,
                    "SpecialInstructions": null,
                    "Causes": [],
                    "CustomFields": [],
                    "Comment": null,
                    "ReceivedEmailCampaignUpdates": true,
                    "DonorId": 583548,
                    "ItemId": 153755,
                    "ItemName": "An auction item",
                    "BidAmount": 136,
                    "MaximumBid": null,
                    "BidStatus": "Winning",
                    "AuctionType": "English",
                    "CampaignFriendlyURL": "https://go.rallyup.com/mycampaign",
                    "CampaignPermanentURL": "https://go.rallyup.com/xxxxxx"
                  }
                ]
              }
            }
          }
        },
        "description": "Retrieves a list of all auction bids placed  across an organization's campaigns"
      }
    },
    "/v3/api/recurringDonations": {
      "get": {
        "tags": [
          "Donations"
        ],
        "summary": "/v3/api/recurringDonations",
        "operationId": "getRecurringdonations",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "id": 24851,
                  "CampaignID": 342,
                  "CampaignTitle": "My Campaign",
                  "FirstName": "FirstName",
                  "LastName": "LastName",
                  "Email": "email@email.com",
                  "RecurringStartDate": "2020-12-17T11:32:31.763Z",
                  "NextChargeDate": "2020-12-17T11:32:31.763Z",
                  "RecurringAmount": 100,
                  "Frequency": "Monthly",
                  "PaymentsCount": 3,
                  "Status": "Active",
                  "PaymentType": "CreditCard",
                  "CreditCardLast4": "1111",
                  "CreditCardType": "visa",
                  "Members": [],
                  "IsAnonymous": false,
                  "InNameOf": null,
                  "MarketingOptIn": false,
                  "MailingAddress": {
                    "MailingFirstName": "FirstName",
                    "MailingLastName": "LastName",
                    "Address1": "AddressLine1",
                    "Address2": "AddressLine2",
                    "City": "City",
                    "State": "CA",
                    "Country": "United States",
                    "ZipCode": "35011",
                    "Phone": "+12345678900"
                  },
                  "GiftAidOptIn": false,
                  "GiftAidInformation": null,
                  "FundCode": null,
                  "SpecialInstructions": null,
                  "Causes": [],
                  "CustomFields": [],
                  "Comment": null,
                  "ReceivedEmailCampaignUpdates": true,
                  "DonorId": 2,
                  "CampaignFriendlyURL": "https://go.rallyup.com/mycampaign",
                  "CampaignPermanentURL": "https://go.rallyup.com/xxxxxx",
                  "RecurringStartDateFormatted": "12/17/2020 3:32AM PST",
                  "NextChargeDateFormatted": "12/17/2020 3:32AM PST"
                }
              }
            }
          }
        },
        "description": "Returns information on any payment made on the campaign for the organization that is part of a recurring donation"
      }
    },
    "/v3/api/liveStreamStatus": {
      "get": {
        "tags": [
          "Streaming"
        ],
        "summary": "/v3/api/liveStreamStatus",
        "operationId": "getLivestreamstatus",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "id": 342,
                  "CampaignID": 342,
                  "CampaignTitle": "My Campaign",
                  "IsStreamActive": true,
                  "StreamUrl": "https://www.youtube.com/watch?v=XXXXXX",
                  "SetupStreamStartDate": "2020-12-17T11:32:31.763Z",
                  "SetupStreamStartDateFormatted": "12/17/2020 3:32AM PST",
                  "StartDate": "2020-12-17T11:32:31.763Z",
                  "StartDateFormatted": "12/17/2020 3:32AM PST",
                  "EndDate": null,
                  "EndDateFormatted": null,
                  "CampaignFriendlyURL": "https://go.rallyup.com/mycampaign",
                  "CampaignPermanentURL": "https://go.rallyup.com/xxxxxx"
                }
              }
            }
          }
        },
        "description": "Retrieves data about a live stream that has started or ended on any of an organization's campaigns"
      }
    },
    "/v3/api/campaignUpdates": {
      "get": {
        "tags": [
          "Campaigns"
        ],
        "summary": "/v3/api/campaignUpdates",
        "operationId": "getCampaignupdates",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "id": 94,
                  "CampaignID": 458,
                  "CampaignTitle": "My Campaign",
                  "UpdateTitle": "Update Title",
                  "UpdateContent": "Update Content",
                  "PostedBy": "FirstName LastName",
                  "Date": "2020-12-17T11:32:31.763Z",
                  "CampaignFriendlyURL": "https://go.rallyup.com/mycampaign",
                  "CampaignPermanentURL": "https://go.rallyup.com/xxxxxx",
                  "DateFormatted": "12/17/2020 3:32AM PST"
                }
              }
            }
          }
        },
        "description": "Retrieves a list of updates posted across an organization's campaigns"
      }
    },
    "/v3/api/raffleWinners": {
      "get": {
        "tags": [
          "Raffles & Sweepstakes"
        ],
        "summary": "/v3/api/raffleWinners",
        "operationId": "getRafflewinners",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "id": 4,
                  "CampaignID": 255,
                  "CampaignTitle": "My raffle",
                  "WinnerID": 2,
                  "WinnerFirstName": "FirstName",
                  "WinnerLastName": "LastName",
                  "WinnerEmail": "email@email.com",
                  "WinnerPhoneNumber": "+12345678900",
                  "Prize": "prize",
                  "WinningTicketNumber": "W196",
                  "CampaignFriendlyURL": "https://go.rallyup.com/mycampaign",
                  "CampaignPermanentURL": "https://go.rallyup.com/xxxxxx"
                }
              }
            }
          }
        },
        "description": "Retrieves a list of objects, where each object represents a combination of a user and a prize that the user won for any of the organization's raffle campaigns"
      }
    },
    "/v1/api/sweepstakesWinners": {
      "get": {
        "tags": [
          "Raffles & Sweepstakes"
        ],
        "summary": "/v3/api/sweepstakesWinners",
        "operationId": "getSweepstakeswinners",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "id": 2,
                  "CampaignID": 253,
                  "CampaignTitle": "My sweepstakes",
                  "WinnerID": 2,
                  "WinnerFirstName": "FirstName",
                  "WinnerLastName": "LastName",
                  "WinnerEmail": "email@email.com",
                  "WinnerPhoneNumber": "+12345678900",
                  "Prize": "Prize",
                  "WinningTicketNumber": "T1",
                  "CampaignFriendlyURL": "https://go.rallyup.com/mycampaign",
                  "CampaignPermanentURL": "https://go.rallyup.com/xxxxxx"
                }
              }
            }
          }
        },
        "description": "Retrieves a list of objects, where each object represents a combination of a user and a prize that the user won for any of the organization's sweepstakes campaigns"
      }
    },
    "/v2/api/auctionWinners": {
      "get": {
        "tags": [
          "Auctions"
        ],
        "summary": "/v2/api/auctionWinners",
        "operationId": "getAuctionwinners",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "id": 25,
                  "CampaignID": 360,
                  "CampaignTitle": "My Auction",
                  "WinnerID": 8808,
                  "WinnerFirstName": "WinnerFirstName",
                  "WinnerLastName": "WinnerLastName",
                  "WinnerEmail": "email@email.com",
                  "WinnerPhoneNumber": "+012345678900",
                  "ItemId": 29,
                  "ItemName": "Item Name",
                  "Category": "Items Category",
                  "WinningBidAmount": 300,
                  "PaymentStatus": "Paid",
                  "CampaignFriendlyURL": "https://go.rallyup.com/mycampaign",
                  "CampaignPermanentURL": "https://go.rallyup.com/xxxxxx"
                }
              }
            }
          }
        },
        "description": "Retrieves a list of objects, where each object represents a combination of a user and a prize that the user won for any of the organization's auction campaigns"
      }
    },
    "/v3/api/activityResults": {
      "get": {
        "tags": [
          "Activities"
        ],
        "summary": "/v3/api/activityResults",
        "operationId": "getActivityresults",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "id": 22,
                  "CampaignID": 308,
                  "CampaignTitle": "My a-thon",
                  "ParticipantName": "FirstName LastName",
                  "TeamName": "Team Name",
                  "ActivityName": "Run",
                  "UnitsTerminologySingular": "Mile",
                  "UnitsTerminologyPlural": "Miles",
                  "UnitsCompleted": 22,
                  "ActivityDate": "2020-12-17T11:32:31.763Z",
                  "CampaignFriendlyURL": "https://go.rallyup.com/mycampaign",
                  "CampaignPermanentURL": "https://go.rallyup.com/xxxxxx",
                  "ActivityDateFormatted": "12/17/2020 3:32AM PST"
                }
              }
            }
          }
        },
        "description": "Retrieves a list of objects that represent activity entered for each campaign on the organization"
      }
    },
    "/v3/api/participants": {
      "get": {
        "tags": [
          "Activities"
        ],
        "summary": "/v3/api/participants",
        "operationId": "getParticipants",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "id": 37039,
                  "CampaignID": 335,
                  "CampaignTitle": "My Campaign",
                  "TeamName": "Team Name",
                  "ParticipantFirstName": "FirstName",
                  "ParticipantLastName": "LastName",
                  "RegistrationOption": "Free Registration",
                  "ParticipantEmailAddress": "email@email.com",
                  "ParticipantPhoneNumber": "+012345678900",
                  "ParticipantMailingAddress": null,
                  "ParticipantActivity": "run",
                  "ParticipantUnitsCompleted": 0,
                  "ParticipantFundraisingGoal": null,
                  "ParticipantUnitsGoal": null,
                  "FundraisingPagePermanentURL": "XXXXXX",
                  "FundraisingPageFriendlyURL": "MyFriendlyURL",
                  "FundraisingPageDescription": "<p>Fundraising Page Description</p>",
                  "ParticipantCustomFields": null,
                  "CampaignFriendlyURL": "https://go.rallyup.com/mycampaign",
                  "CampaignPermanentURL": "https://go.rallyup.com/xxxxxx"
                }
              }
            }
          }
        },
        "description": "Retrieves a list of objects that represent participants registered on all campaigns across the organization"
      }
    },
    "/v3/api/teams": {
      "get": {
        "tags": [
          "Activities"
        ],
        "summary": "/v3/api/teams",
        "operationId": "getTeams",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "id": 2895,
                  "CampaignID": 342,
                  "CampaignTitle": "My Campaign",
                  "TeamName": "Team Name",
                  "RegistrationOption": "Free Registration",
                  "FundraisingPageDescription": "<p>Fundraising Page Description</p>",
                  "TeamEmailAddress": "email@email.com",
                  "TeamFundraisingGoal": null,
                  "FundraisingPagePermanentURL": "XXXXXX",
                  "FundraisingPageFriendlyURL": "MyFriendlyURL",
                  "ParticipantCustomFields": [],
                  "CampaignFriendlyURL": "https://go.rallyup.com/mycampaign",
                  "CampaignPermanentURL": "https://go.rallyup.com/xxxxxx"
                }
              }
            }
          }
        },
        "description": "Retrieves a list of objects that represent teams registered on all campaigns across the organization"
      }
    },
    "/v3/api/contactOrganizerMessages": {
      "get": {
        "tags": [
          "Communication"
        ],
        "summary": "/v3/api/contactOrganizerMessages",
        "operationId": "getContactorganizermessages",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "id": 1,
                  "CampaignID": 123,
                  "CampaignTitle": "Campaign Title",
                  "SenderEmail": "sender@email.com",
                  "SenderName": "SenderFirstName SenderLastName",
                  "Message": "Message body",
                  "MessageSubject": "Message subject",
                  "CampaignFriendlyURL": "https://go.rallyup.com/mycampaign",
                  "CampaignPermanentURL": "https://go.rallyup.com/xxxxxx"
                }
              }
            }
          }
        },
        "description": "Retrieves information about messages being sent to an Organization through the Contact Organizer function"
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "description": "Bearer token obtained from the /v1/token endpoint"
      }
    },
    "schemas": {}
  },
  "security": [
    {
      "bearerAuth": []
    }
  ]
}